title: Onyebuchi Chukwumaife

logo: buchi.png

description: I am a Data analyst with wide experience using Advanced Excel for data entry, 
SQL for data interogation and manipulation, 
R for machine learning, 
Python for data interrogation and manipulation, 
Power Bi for data visualization.

#show_downloads: true

#google_analytics:

theme: jekyll-theme-minimal
